language: java
sudo: false # faster builds
jdk:
  - openjdk8
branches: # build only on these branches
  only:
    #- master
    - develop
script:
  - mvn package

after_success:
  - bash <(curl -s https://codecov.io/bash)

