language: java
sudo: false # faster builds
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
  - openjdk12
branches: # build only on these branches
  only:
    - master
    - dev
script:
  - mvn test
  - mvn cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

matrix:
  allow_failures:
    - jdk: openjdk10
    - jdk: openjdk11
    - jdk: openjdk12
