language: java
sudo: false # faster builds
jdk:
  - openjdk8
branches: # build only on these branches
  only:
    #- master
    - develop

install:
  mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
