language: java
sudo: false # faster builds
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
branches: # build only on these branches
  only:
    - master
    - develop
script:
  - "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

